//PIC16628A

INT CONTROL = 0XFF ;

void main (){

    // DEFININDO COMO SAIDA
    TRISB = 0;
    //DEFINIDO ESTADO LOGICO DOS 8 PINOS (0XFF = 11111111 = 255)
    PORTB = 0xFF;

    WHILE(1){
        PORTB = CONTROL;
        DELAY_MS(300);

        //SHIT LEFT = DESLOCAMENTO DE BITS PARA A ESQUERDA
        CONTROL = CONTROL << 1;

        // CASO CHEGUE AO VALOR 0, O VALOR DE CONTROL É RESETADO PARA 0XFF
        IF(CONTROL == 0) CONTROL = 0XFF;
    }

}